# import files
# import = ["~/.config/alacritty/filename", ...]

live_config_reload = true

[window]
padding = { x = 4, y = 4 }
dynamic_padding = false
opacity = 0.9
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "dark"
decorations = "none"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
